name: rlenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12  # Latest stable Python version as of April 2025
  - pip
  - pip:
    - numpy
    - pandas
    - matplotlib  # Common data science packages as examples
    - pygame      # Added pygame package
    - PyOpenGL 
    - PyOpenGL_accelerate
    - scipy
    - torch
    - gymnasium>=0.29.0
    - pettingzoo>=1.24.0
    - stable-baselines3[extra]>=2.0.0
    - shimmy>=1.3.0
    - wandb>=0.15.0
    - tensorboard>=2.13.0
    - tqdm>=4.65.0
